= Recherche Java Spring JSON Verarbeitung

== Daten von JSON zu Java oder umgekehrt bearbeiten

=== Libraries
1. Jackson
2. Gson by Google

==== Gson
- Entwickelt von Google
- Einfach und unkompliziert

==== Jackson
- Integriert in verschiedene Frameworks (z.B. Spring)
- Wenn die relevanten Jackson-Abh채ngigkeiten (`jackson-databind`) im Klassenpfad Ihres Spring-Projekts enthalten sind, verwendet Spring automatisch Jackson f체r die Verarbeitung von JSON-Daten.
- Ebenso konvertiert Jackson empfangene JSON-Daten (z.B. von einer externen API) in einem Spring-Controller in Java-Objekte (Deserialisierung).

== Installation in einem Java Spring Projekt

F체gen Sie die folgenden Abh채ngigkeiten in Ihrer `pom.xml` Datei hinzu:

```xml
<dependencies>
    <!-- Jackson Dependency -->
    <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-databind</artifactId>
        <version>2.13.0</version>
    </dependency>
    <!-- Gson Dependency -->
    <dependency>
        <groupId>com.google.code.gson</groupId>
        <artifactId>gson</artifactId>
        <version>2.8.9</version>
    </dependency>
</dependencies>




== Beispiel
https://github.com/moud2/Musikverwaltung/blob/main/src/main/java/MusicFileUtil.java
